# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - tonkotsu-cal(stage)

on:
  push:
    branches:
      - CDornbush-patch-4

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'tonkotsu-cal(stage)'
        slot-name: 'stage'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_93057ab7af494674a8cd3527503d4699 }}
        package: .